// <auto-generated />
using System;
using BingeWatcher.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BingeWatcher.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190912185047_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BingeWatcher.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Director")
                        .IsRequired();

                    b.Property<int>("Genre");

                    b.Property<bool>("IsActive");

                    b.Property<string>("PosterSource");

                    b.Property<string>("Provider");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Source");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Writer");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new { Id = 1, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 273, DateTimeKind.Local), Director = "Reżyser kina akcji", Genre = 0, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film akcji nr 1" },
                        new { Id = 2, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina akcji", Genre = 0, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film akcji nr 2" },
                        new { Id = 3, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina akcji", Genre = 0, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film akcji nr 3" },
                        new { Id = 4, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina przygodowego", Genre = 1, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film przygodowy nr 1" },
                        new { Id = 5, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina przygodowego", Genre = 1, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film przygodowy nr 2" },
                        new { Id = 6, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina przygodowego", Genre = 1, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film przygodowy nr 3" },
                        new { Id = 7, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina komediowego", Genre = 2, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film komediowy nr 1" },
                        new { Id = 8, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina komediowego", Genre = 2, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film komediowy nr 2" },
                        new { Id = 9, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina komediowego", Genre = 2, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film komediowy nr 3" },
                        new { Id = 10, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina kryminalnego", Genre = 3, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film kryminalny nr 1" },
                        new { Id = 11, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina kryminalnego", Genre = 3, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film kryminalny nr 2" },
                        new { Id = 12, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina kryminalnego", Genre = 3, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film kryminalny nr 3" },
                        new { Id = 13, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dramatycznego", Genre = 4, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dramatyczny nr 1" },
                        new { Id = 14, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dramatycznego", Genre = 4, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dramatyczny nr 2" },
                        new { Id = 15, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dramatycznego", Genre = 4, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dramatyczny nr 3" },
                        new { Id = 16, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina fantasy", Genre = 5, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film fantasy nr 1" },
                        new { Id = 17, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina fantasy", Genre = 5, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film fantasy nr 2" },
                        new { Id = 18, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina fantasy", Genre = 5, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film fantasy nr 3" },
                        new { Id = 19, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina historycznego", Genre = 6, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film historyczny nr 1" },
                        new { Id = 20, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina historycznego", Genre = 6, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film historyczny nr 2" },
                        new { Id = 21, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina historycznego", Genre = 6, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film historyczny nr 3" },
                        new { Id = 22, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina horror", Genre = 7, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film horror nr 1" },
                        new { Id = 23, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina horror", Genre = 7, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film horror nr 2" },
                        new { Id = 24, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina horror", Genre = 7, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film horror nr 3" },
                        new { Id = 25, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina politycznego", Genre = 8, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film polityczny nr 1" },
                        new { Id = 26, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina politycznego", Genre = 8, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film polityczny nr 2" },
                        new { Id = 27, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina politycznego", Genre = 8, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film polityczny nr 3" },
                        new { Id = 28, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina romantycznego", Genre = 9, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film romantyczny nr 1" },
                        new { Id = 29, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina romantycznego", Genre = 9, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film romantyczny nr 2" },
                        new { Id = 30, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina romantycznego", Genre = 9, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film romantyczny nr 3" },
                        new { Id = 31, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina science fiction", Genre = 10, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film science fiction nr 1" },
                        new { Id = 32, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina science fiction", Genre = 10, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film science fiction nr 2" },
                        new { Id = 33, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina science fiction", Genre = 10, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film science fiction nr 3" },
                        new { Id = 34, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dreszczowców", Genre = 11, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dreszczowiec nr 1" },
                        new { Id = 35, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dreszczowców", Genre = 11, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dreszczowiec nr 2" },
                        new { Id = 36, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina dreszczowców", Genre = 11, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film dreszczowiec nr 3" },
                        new { Id = 37, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina western", Genre = 12, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film western nr 1" },
                        new { Id = 38, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina western", Genre = 12, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film western nr 2" },
                        new { Id = 39, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina western", Genre = 12, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film western nr 3" },
                        new { Id = 40, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina musical", Genre = 13, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film musical nr 1" },
                        new { Id = 41, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina musical", Genre = 13, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film musical nr 2" },
                        new { Id = 42, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina musical", Genre = 13, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film musical nr 3" },
                        new { Id = 43, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina anime", Genre = 14, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film anime nr 1" },
                        new { Id = 44, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina anime", Genre = 14, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film anime nr 2" },
                        new { Id = 45, AddedDate = new DateTime(2019, 9, 12, 20, 50, 47, 280, DateTimeKind.Local), Director = "Reżyser kina anime", Genre = 14, IsActive = true, ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Film anime nr 3" }
                    );
                });

            modelBuilder.Entity("BingeWatcher.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, FirstName = "Jan", LastName = "Kowalski", UserName = "jkowalski" },
                        new { Id = 2, FirstName = "Janina", LastName = "Kowalska", UserName = "jkowalska" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
